version: '2'

services:
  # ELASTICSEARCH
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
    container_name: elasticsearch
  
  # KIBANA
  kibana:
    image: kibana
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "80:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    container_name: kibana
  
  # SHIPPER
  logstash-shipper:
    image: logstash
    volumes:
      - ./logs:/tmp/logs
      - ./logstash-shipper:/etc/logstash
    networks:
      - docker_elk
    stdin_open: true
    tty: true
    container_name: logstash-shipper
    depends_on:
      - elasticsearch

  # FILTER
  logstash-filter:
    image: logstash
    volumes:
      - ./logstash-filter:/etc/logstash
    networks:
      - docker_elk
    container_name: logstash-filter
    depends_on:
      - elasticsearch

  # REDIS
  redis:
    image: redis
    ports:
        - "6379"
    networks:
      - docker_elk
    container_name: redis
  
networks:
  docker_elk:
    driver: bridge
